version: "3.8"

services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
      - otel-collector

  backend:
    build: ./backend
    ports:
      - "3050:3050"
    depends_on:
      - mongo
      - otel-collector

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  otel-collector:
    image: otel/opentelemetry-collector:latest
    command: ["--config=/etc/otel/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel/otel-collector-config.yaml
    ports:
      #- "4317:4317"   # gRPC OTLP
      - "4318:4318"   # HTTP OTLP
      - "55681:55681" # legacy
    depends_on:
      - jaeger

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686" # Jaeger UI
      - "4317:4317"   # OTLP gRPC
      - "6831:6831/udp" # Jaeger Thrift (optional)
    environment:
      COLLECTOR_OTLP_ENABLED: true

volumes:
  mongo-data: